server:
  port: 9401 #??
spring:
  application:
    name: sentinel-service #??? sentinel-service-sentinel
  cloud:
    sentinel:
      transport:
        #?? Sentinel dashboard ??
        dashboard: localhost:8080
        #??8719????????????8719????+1??,???????????
        port: 8719
      datasource:
        ds:
          nacos:
              #Nacos??????(??)??
              server-addr: localhost:8848
              data-id: sentinel-service-sentinel
              group-id: DEFAULT_GROUP
              data-type: json
              rule-type: flow
management:
  endpoints:
    web:
      exposure:
        include: '*'
