server:
  port: 8001 #?????
spring:
  application:
    name: microServiceCloudProviderDept  #?????????????????????
  ################################################## JDBC ????  ##########################################
  datasource:
    username: root        #????????
    password: 123456        #???????
    #???url
    url: jdbc:mysql://192.168.80.148:3306/ddpay?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver                  #?????
############################### ??? spring.config.import=configserver:##################
#  cloud:
#    config:
#      enabled: false
###################################### MyBatis ?? ######################################
mybatis:
  # ?? mapper.xml ???
  mapper-locations: classpath:mybatis/mapper/*.xml
  #????????,?????????????? mapper.xml ??????????????
  type-aliases-package: net.biancheng.c.entity
  configuration:
    #???????????????????
    map-underscore-to-camel-case: true
########################################### Spring cloud ???????? ip ??###############################################
eureka:
  client: #??????? eureka ?????
    service-url:
      defaultZone: http://localhost:7001/eureka  #????? 7001????? application.yml ?????????? ?????
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  #?????? Eureka Server ??
  instance:
    instance-id: spring-cloud-provider-8001 #?????????
    prefer-ip-address: true  #??????? ip ??
########################################## spring cloud ?? Spring Boot actuator ??????###################################
# Spring Boot 2.50? actuator ???????????????? heath ????????*????????????
management:
  endpoints:
    web:
      exposure:
        include: "*"   # * ?yaml ???????????????
info:
  app.name: micro-service-cloud-provider-dept
  company.name: c.biancheng.net
  build.aetifactId: @project.artifactId@
  build.version: @project.version@
