
server:
  port: 80 #???
############################################# Spring Cloud Ribbon ??????##########################
eureka:
  client:
    register-with-eureka: false #??????????????????????????
    fetch-registry: true  #????????????????????????
    service-url:
      defaultZone: http://localhost:7001/eureka/ #????????