server:
  port: 9901  #???
spring:
  application:
    name: spring-cloud-alibaba-consumer #???
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #Nacos server ???
#?????????????????????????????? Controller ?????????????
service-url:
  nacos-user-service: http://spring-cloud-alibaba-provider #?????????
