server:
  port: 7001  #? Module ????


#eureka:
#  instance:
#    hostname: localhost #eureka?????????
#  client:
#    register-with-eureka: false #false?????????????
#    fetch-registry: false #false??????????????????????????????????
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #?????????
#

eureka:
  instance:
    hostname: eureka7001.com #eureka????????
  client:
    register-with-eureka: false #false ?????????????
    fetch-registry: false #false ??????????????????????????????????
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #???
#      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #??? ???? Eureka Server ??? 7003 ? 7003 ??????????? Eureka Server ??
