server:
  port: 9003 #??
spring:
  application:
    name: spring-cloud-alibaba-provider-mysql
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  ######################### ????? #################################
  datasource:
    username: root        #????????
    password: 123456        #???????
    url: jdbc:mysql://192.168.80.148:3306/ddpay       #???url
    driver-class-name: com.mysql.jdbc.Driver
management:
  endpoints:
    web:
      exposure:
        include: "*"   # * ?yaml ???????????????
###################################### MyBatis ?? ######################################
mybatis:
  # ?? mapper.xml ???
  mapper-locations: classpath:mybatis/mapper/*.xml
  #????????,?????????????? mapper.xml ??????????????
  type-aliases-package: com.example.springcloudalibabaprovidermysql9003.entity
  configuration:
    #???????????????????
    map-underscore-to-camel-case: true
